spring:
  application:
    name: mongodbTut
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase
      #      uri: mongodb+srv://harshil-8705:123atHarshilhash8705plus5101922@mycluster.vwiok6n.mongodb.net/ecommerceDB?retryWrites=true&w=majority
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true
server:
  port: 9090
