spring:
  application:
    name: mongodbTut
  data:
    mongodb:
      uri: mongodb://localhost:27017/mydatabase
      auto-index-creation: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 9090

logging:
  level:
    org.springframework.data.mongodb:
      core.MongoTemplate: DEBUG
